version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nestjs_interview_db
      POSTGRES_USER: nestjs_interview_user
      POSTGRES_PASSWORD: nestjs_interview_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: